module.exports = {
  angular: {
    build: 'build',
    chore: 'chore',
    ci: 'ci',
    docs: 'docs',
    feat: 'feat',
    fix: 'fix',
    perf: 'perf',
    refactor: 'refactor',
    style: 'style',
    test: 'test',
  },
  atom: {
    apple: '🍎',
    code: '🔥',
    'chore(linter-warning)': '👕',
    'chore(memory)': '🚱',
    ci: '💚',
    docs: '📝',
    downgrade: '⬇️',
    fix: '🐛',
    'fix(ci)': '💚',
    memory: '🚱',
    perf: '🐎',
    linter: '👕',
    linux: '🐧',
    remove: '🔥',
    security: '🔒',
    style: '🎨',
    test: '✅',
    upgrade: '⬆️',
    windows: '🏁'
  },
  ember: {
    chore: 'CLEANUP beta',
    clean: 'CLEANUP beta',
    docs: 'DOC canary',
    feat: 'FEATURE',
    fix: 'BUGFIX canary',
    security: 'SECURITY cve'
  },
  eslint: {
    breaking: 'Breaking',
    build: 'Build',
    chore: 'Chore',
    docs: 'Docs',
    feat: 'New',
    fix: 'Fix',
    update: 'Update',
    upgrade: 'Upgrade'
  },
  jshint: {
    chore: 'CHORE',
    docs: 'DOCS',
    feat: 'FEAT',
    fix: 'FIX',
    test: 'DOCS'
  },
  gitmoji: {
    feat: '✨',
    fix: '🐛',
    docs: '📝',
    style: '🎨',
    refactor: '♻️',
    perf: '⚡️',
    test: '✅',
    build: '📦️',
    ci: '👷',
    chore: '🔧'
  },
}